package com.example.murphysl.autoupdatetest.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.murphysl.autoupdatetest.db.ThreadInfo;
import com.example.murphysl.autoupdatetest.db.FileInfo;

import com.example.murphysl.autoupdatetest.db.ThreadInfoDao;
import com.example.murphysl.autoupdatetest.db.FileInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig threadInfoDaoConfig;
    private final DaoConfig fileInfoDaoConfig;

    private final ThreadInfoDao threadInfoDao;
    private final FileInfoDao fileInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        threadInfoDaoConfig = daoConfigMap.get(ThreadInfoDao.class).clone();
        threadInfoDaoConfig.initIdentityScope(type);

        fileInfoDaoConfig = daoConfigMap.get(FileInfoDao.class).clone();
        fileInfoDaoConfig.initIdentityScope(type);

        threadInfoDao = new ThreadInfoDao(threadInfoDaoConfig, this);
        fileInfoDao = new FileInfoDao(fileInfoDaoConfig, this);

        registerDao(ThreadInfo.class, threadInfoDao);
        registerDao(FileInfo.class, fileInfoDao);
    }
    
    public void clear() {
        threadInfoDaoConfig.clearIdentityScope();
        fileInfoDaoConfig.clearIdentityScope();
    }

    public ThreadInfoDao getThreadInfoDao() {
        return threadInfoDao;
    }

    public FileInfoDao getFileInfoDao() {
        return fileInfoDao;
    }

}
