package com.example.murphysl.todo.db.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "todo".
 */
@Entity(nameInDb = "todo")
public class Todo {

    @Id
    private Long id;
    private String title;
    private String content;
    private String createTime;

    @Generated(hash = 1698043777)
    public Todo() {
    }

    public Todo(Long id) {
        this.id = id;
    }

    @Generated(hash = 902714190)
    public Todo(Long id, String title, String content, String createTime) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.createTime = createTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

}
