/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_nuc_androidlab_ndkdemo_JNIUtils */

#ifndef _Included_cn_edu_nuc_androidlab_ndkdemo_JNIUtils
#define _Included_cn_edu_nuc_androidlab_ndkdemo_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_edu_nuc_androidlab_ndkdemo_JNIUtils
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_edu_nuc_androidlab_ndkdemo_JNIUtils_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
